# base.py
# Abstract base classes for multimodal content processing services

# Defines the abstract interfaces for all multimodal processors including
# audio transcription, OCR text extraction, and image/diagram analysis.
# Also includes data models for transcription results, OCR results, and
# image descriptions used throughout the multimodal pipeline.

# @see: audio.py, ocr.py, image.py - Concrete implementations
# @note: All methods are abstract and must be implemented by subclasses

from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, AsyncIterator, Dict, List, Optional, Tuple, Union

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Configuration and Result Models
# ---------------------------------------------------------------------------


class ProcessConfig(BaseModel):
    """Configuration for multimodal processing operations."""

    language: str = "en"
    enhance_quality: bool = True
    include_metadata: bool = True
    timeout_seconds: int = 300


class ProcessResult(BaseModel):
    """Generic result from multimodal processing."""

    success: bool
    content: str
    content_type: str
    confidence: float
    processing_time_seconds: float
    metadata: Dict[str, Any] = Field(default_factory=dict)
    errors: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Transcription Models
# ---------------------------------------------------------------------------


class WordTimestamp(BaseModel):
    """Individual word with timing information."""

    word: str
    start_time: float
    end_time: float
    confidence: float


class TranscriptionSegment(BaseModel):
    """A segment of transcribed audio with timing and speaker info."""

    start_time: float
    end_time: float
    text: str
    speaker: Optional[str] = None
    confidence: float


class TranscriptionResult(BaseModel):
    """Complete transcription result from audio processing."""

    text: str
    segments: List[TranscriptionSegment]
    duration_seconds: float
    language: str
    confidence: float
    word_timestamps: Optional[List[WordTimestamp]] = None


# ---------------------------------------------------------------------------
# OCR Models
# ---------------------------------------------------------------------------


class BoundingBox(BaseModel):
    """Bounding box coordinates for detected text or objects."""

    x: int
    y: int
    width: int
    height: int
    confidence: float = 1.0


class OCRResult(BaseModel):
    """Result from OCR text extraction."""

    text: str
    page_number: Optional[int] = None
    bounding_boxes: List[BoundingBox] = Field(default_factory=list)
    confidence: float
    language: str


# ---------------------------------------------------------------------------
# Image/Diagram Models
# ---------------------------------------------------------------------------


class DiagramInfo(BaseModel):
    """Information about an extracted diagram or figure."""

    image_data: bytes
    page_number: int
    position: Tuple[int, int, int, int]  # x, y, width, height
    diagram_type: Optional[str] = None  # flowchart, chart, table, etc.
    extracted_text: Optional[str] = None


class ImageDescription(BaseModel):
    """Description of an image generated by vision LLM."""

    description: str
    detected_objects: List[str] = Field(default_factory=list)
    detected_text: List[str] = Field(default_factory=list)
    embedding: Optional[List[float]] = None


# ---------------------------------------------------------------------------
# Abstract Base Classes
# ---------------------------------------------------------------------------


class MultimodalProcessor(ABC):
    """
    Base class for all multimodal processors.

    Defines the common interface for audio, OCR, and image processing services.
    All concrete implementations must implement these abstract methods.
    """

    @abstractmethod
    async def process(
        self, source: Union[str, bytes], config: ProcessConfig
    ) -> ProcessResult:
        """
        Process multimodal content and return structured result.

        Args:
            source: File path or raw bytes of content to process.
            config: Processing configuration options.

        Returns:
            ProcessResult with extracted content and metadata.
        """
        pass

    @abstractmethod
    def supported_formats(self) -> List[str]:
        """
        Return list of supported file formats.

        Returns:
            List of file extensions (without dot) e.g., ["mp3", "wav"].
        """
        pass

    @abstractmethod
    async def health_check(self) -> bool:
        """
        Check if processor is available and configured.

        Returns:
            True if processor is ready to accept requests.
        """
        pass


class AudioProcessor(MultimodalProcessor):
    """
    Abstract base for audio transcription services.

    Extends MultimodalProcessor with audio-specific transcription methods
    including streaming support for real-time transcription.
    """

    @abstractmethod
    async def transcribe(
        self, audio_source: str, language: str = "en"
    ) -> TranscriptionResult:
        """
        Transcribe audio file to text.

        Args:
            audio_source: Path to audio file.
            language: Language code for transcription (default: "en").

        Returns:
            TranscriptionResult with text and timing information.
        """
        pass

    @abstractmethod
    async def transcribe_stream(
        self, audio_stream: AsyncIterator[bytes]
    ) -> AsyncIterator[TranscriptionSegment]:
        """
        Transcribe audio stream in real-time.

        Args:
            audio_stream: Async iterator yielding audio chunks.

        Yields:
            TranscriptionSegment as they are recognized.
        """
        pass


class OCRProcessor(MultimodalProcessor):
    """
    Abstract base for OCR services.

    Extends MultimodalProcessor with OCR-specific methods for extracting
    text from images and PDF documents.
    """

    @abstractmethod
    async def extract_text(self, image_source: Union[str, bytes]) -> OCRResult:
        """
        Extract text from a single image.

        Args:
            image_source: Path to image file or raw image bytes.

        Returns:
            OCRResult with extracted text and bounding boxes.
        """
        pass

    @abstractmethod
    async def extract_from_pdf(
        self, pdf_path: str, pages: Optional[List[int]] = None
    ) -> List[OCRResult]:
        """
        Extract text from PDF pages using OCR.

        Args:
            pdf_path: Path to PDF file.
            pages: Optional list of page numbers to process (0-indexed).
                   If None, processes all pages.

        Returns:
            List of OCRResult, one per processed page.
        """
        pass


class ImageProcessor(MultimodalProcessor):
    """
    Abstract base for image analysis services.

    Extends MultimodalProcessor with image-specific methods for extracting
    diagrams and generating image descriptions using vision LLMs.
    """

    @abstractmethod
    async def extract_diagrams(self, document_path: str) -> List[DiagramInfo]:
        """
        Extract all diagrams/figures from a document.

        Args:
            document_path: Path to PDF, DOCX, or PPTX document.

        Returns:
            List of DiagramInfo with extracted images and metadata.
        """
        pass

    @abstractmethod
    async def describe_image(self, image_source: Union[str, bytes]) -> ImageDescription:
        """
        Generate text description of an image using vision LLM.

        Args:
            image_source: Path to image file or raw image bytes.

        Returns:
            ImageDescription with textual description and detected elements.
        """
        pass
