/**
 * ============================================================================
 * FILE: vite-env.d.ts
 * LOCATION: frontend/src/vite-env.d.ts
 * ============================================================================
 *
 * PURPOSE:
 *    Vite type declarations for environment and import types. Extends
 *    TypeScript's understanding of Vite-specific imports.
 *
 * ROLE IN PROJECT:
 *    Auto-generated type reference file that tells TypeScript about
 *    Vite's module resolution and import types.
 *
 * KEY DECLARATIONS:
 *    - Reference to vite/client for Vite-specific imports
 *
 * DEPENDENCIES:
 *    - External: vite/client (Vite's type definitions)
 *    - Internal: None
 *
 * @see: https://vitejs.dev/guide/features.html#typescript
 * @note: Auto-generated by Vite, may be overwritten on update
 */
/// <reference types="vite/client" />
